<?php if (!empty($this->gallery)) { ?>
    <div class="row-fluid">
        <h3>Delete <?php echo $this->gallery->name; ?></h3>
    </div>
    <div class="row-fluid">
        <p>Are you sure you want to permanently delete this <?php $this->gallery->name ?> ?</p>
        <p>This action is not reversible!</p>
        <p>&nbsp;</p>
    </div>
    <div class="row-fluid">
        <div class="span2">
            <input class="btn btn-block link-to-back" value="Cancel"/>
        </div>
        <div class="span2">
            <form method="post">
                <input class="btn btn-block btn-danger" type="submit" value="Delete"/>
            </form>
        </div>
    </div>
<?php } ?>
