<form method="post" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="span4">
            <label><?php echo $this->form->name->getLabel(); ?></label>
            <?php echo $this->form->name; ?>
        </div>
        <div class="span4 offset1">
            <label><?php echo $this->form->share_status->getLabel(); ?></label>
            <?php echo $this->form->share_status; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <label><?php echo $this->form->file->getLabel(); ?></label>
            <?php echo $this->form->file; ?>
            <p><?php echo $this->form->file->getDescription(); ?></p>
            <?php if ($this->form->file->hasErrors()) { ?>
                <ul class="errors">
                    <?php foreach ($this->form->file->getmessage() as $message) { ?>
                        <li>
                            <?php echo $message; ?>
                        </li>
                    <?php } ?>
                </ul>
            <?php } ?>
        </div>
        <?php if (!empty($this->file)) { ?>
            <div class="span4">
                <p>&nbsp;</p>
                <a href="<?php echo $this->getResource($this->file, 'gallery', 'uploads'); ?>"><i class="icon-download"></i>Download Old File</a>
            </div>
        <?php } ?>
    </div>
    <div class="row-fluid">&nbsp;</div>
    <div class="row-fluid">
        <div class="span3">
            <input class="btn btn-primary btn-block btn-input" type="submit" value="Upload" />
        </div>
    </div>
</form>