<?php
$this->headScript()->appendFile($this->baseUrl() . '/resources/js/jquery.colorbox-min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/resources/css/colorbox.css');

$horizontalListCount = 3;
$listCount = $this->paginator->getCurrentItemCount();
?>
<?php if ($listCount) { ?>
    <div class="list-items">
        <?php foreach ($this->paginator as $key => $item) { ?>
            <?php if ($key % $horizontalListCount == 0) { ?>
                <div class="row-fluid">
                <?php } ?>
                <div class="span4 list-item border-all padding-all-5">
                    <div class="row-fluid center-aligned">
                        <?php if (!empty($item->file)) { ?>
                            <a class="js-colorbox" rel="gallery" href="<?php echo $this->getResource($item->file, 'gallery', 'uploads'); ?>">
                                <img src="<?php echo $this->timthumb($this->getResource($item->file, 'gallery', 'uploads'), 280, 280, 2); ?>" />
                            </a>
                        <?php } else { ?>
                            <img src="<?php echo $this->getResource('no-image-280.png'); ?>" />
                        <?php } ?>
                    </div>
                    <div class="row-fluid margin-top-10">
                        <?php if ($this->isAdmin || $this->user() && $item->added_by == $this->user()->id) { ?>
                            <div class="btn-group pull-right">
                                <button data-toggle="dropdown" class="btn btn-small drop-toggle">Action<span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'edit', 'id' => $item->id), NULL, TRUE); ?>">Edit</a> 
                                    </li>
                                    <?php
                                    if ($this->pending === TRUE) {
                                        $this->shareOption($item);
                                    }
                                    ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'delete', 'id' => $item->id), NULL, TRUE) ?>">Delete</a>
                                    </li>
                                </ul>
                            </div>
                        <?php } ?>
                        <p class="no-margin-bottom"><?php echo $item->username; ?></p>
                        <h4 class="no-margin"><?php echo $item->name; ?></h4>
                    </div>
                    <div class="row-fluid margin-top-10">
                        <div class="pull-left">
                            <?php $this->likebutton($item); ?>
                        </div>
                        <div class="pull-right">
                            <?php $this->sharebutton($item); ?>
                        </div>
                    </div>
                </div>
                <?php $keyPlusOne = $key + 1; ?>
                <?php if ($keyPlusOne % $horizontalListCount == 0 || $keyPlusOne == $listCount) { ?>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php } else { ?>
    <div class="tumbleweed"></div>
<?php } ?>

