<?php if ($this->paginator->count()) { ?>
    <div class="list-items">
        <?php foreach ($this->paginator as $item) { ?>
            <div class="row-fluid list-item">
                <div class="span2">
                    <div class="row-fluid thumb">
                        <img src="<?php echo $this->getResource($item->thumbnail, 'thumbnails', 'uploads'); ?>" />
                    </div>
                    <div class="row-fluid margin-top-10">
                        <button class="btn btn-small"><i class="icon-heart"></i> Like</button>
                        <button class="btn btn-small"><i class="icon-share"></i> Share</button>
                    </div>
                </div>
                <div class="span10">
                    <p class="no-margin-bottom"><?php echo $item->username; ?></p>
                    <h4 class="no-margin"><?php echo $item->name; ?></h4>
                    <p><?php echo $item->type; ?> <strong>by <?php echo $item->artist; ?></strong></p>
                    <div class="row-fluid">
                        <div class="span11">
                            <?php echo $this->jPlayer($item->file, $item->name); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php } ?>