<?php if ($this->paginator->count()) { ?>
    <div class="list-items">
        <?php foreach ($this->paginator as $item) { ?>
            <?php echo $this->partial('media/partial-media.phtml', array('item' => $item, 'pending' => $this->pending, 'shared' => $this->shared)); ?>
        <?php } ?>
    </div>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php } else { ?>
    <div class="tumbleweed"></div>
<?php } ?>