<?php if ($this->paginator->count()) { ?>
    <div class="list-items">
        <?php foreach ($this->paginator as $item) { ?>
            <div class="row-fluid list-item">
                <div class="span2">
                    <div class="row-fluid thumb">
                        <?php if (!empty($item->thumbnail)) { ?>
                            <img src="<?php echo $this->getResource($item->thumbnail, 'thumbnails', 'uploads'); ?>" />
                        <?php } else { ?>
                            <img src="<?php echo $this->getResource('no-image-140.png'); ?>" />    
                        <?php } ?>
                    </div>
                    <div class="row-fluid margin-top-10">
                        <button class="btn btn-small"><i class="icon-heart"></i> Like</button>
                        <button class="btn btn-small"><i class="icon-share"></i> Share</button>
                    </div>
                </div>
                <div class="span10">
                    <?php if ($item->added_by == $this->user()->id) { ?>
                        <a class="btn btn-small pull-right" href="<?php echo $this->url(array('controller' => 'media', 'action' => 'edit', 'id' => $item->id), NULL, TRUE); ?>">Edit</a>
                    <?php } ?>
                    <p class="no-margin-bottom"><?php echo $item->username; ?></p>
                    <h4 class="no-margin"><?php echo $item->name; ?></h4>
                    <p><?php echo $item->type; ?> <strong>by <?php echo $item->artist; ?></strong></p>
                    <div class="row-fluid">
                        <div class="span11">
                            <?php echo $this->jPlayer($item->file, $item->name); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php echo $this->paginationControl($this->paginator); ?>
<?php } else { ?>
    <div class="tumbleweed"></div>
<?php } ?>