<?php
$item = $this->item;
?>
<div class="row-fluid list-item">
    <div class="span2">
        <div class="row-fluid thumb">
            <?php if (!empty($item->thumbnail)) { ?>
                <img src="<?php echo $this->timthumb($this->getResource($item->thumbnail, 'thumbnails', 'uploads'), 140, 140, 2); ?>" />
            <?php } else { ?>
                <img src="<?php echo $this->getResource('no-image-140.png'); ?>" />    
            <?php } ?>
        </div>
        <div class="row-fluid margin-top-10">
            <?php $this->likeButton($item); ?>
        </div>
        <div class="row-fluid margin-top-5">
            <?php $this->shareButton($item); ?>
        </div>
    </div>
    <div class="span10">
        <?php if ($this->isAdmin() || $this->user() && $item->added_by == $this->user()->id) { ?>
            <div class="btn-group pull-right">
                <button data-toggle="dropdown" class="btn btn-small dropdown-toggle">Action <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'media', 'action' => 'edit', 'id' => $item->id, 'pending' => $this->pending, 'shared' => $this->shared), NULL, TRUE); ?>">Edit</a>
                    </li>
                    <?php
                    if ($this->pending === TRUE) {
                        $this->shareOption($item);
                    }
                    ?>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'media', 'action' => 'delete', 'id' => $item->id, 'pending' => $this->pending, 'shared' => $this->shared), NULL, TRUE); ?>">Delete</a>
                    </li>
                </ul>
            </div>
        <?php } ?>
        <p class="no-margin-bottom"><?php echo $item->username; ?></p>
        <h4 class="no-margin"><?php echo $item->name; ?></h4>
        <p><?php echo $item->type; ?> <strong>by <?php echo $item->artist; ?></strong></p>
        <div class="row-fluid">
            <div class="span11">
                <?php echo $this->jPlayer($item->file, $item->name); ?>
            </div>
        </div>
    </div>
</div>