<?php if (isset($this->mostLiked['media']) && !empty($this->mostLiked['media'])) { ?>
    <div class="sub-content">
        <h2 class="border-bottom">Media</h2>
        <div class="row-fluid list-items">
            <?php foreach ($this->mostLiked['media'] as $item) { ?>
                <div id="media<?php echo $item->id; ?>">
                    <?php echo $this->partial('media/partial-media.phtml', array('item' => $item)); ?>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>
<?php if (isset($this->mostLiked['library']) && !empty($this->mostLiked['library'])) { ?>
    <div class="sub-content">
        <h2 class="border-bottom">Library</h2>
        <div class="list-items">
            <?php foreach ($this->mostLiked['library'] as $item) { ?>
                <div id="library<?php echo $item->id; ?>">
                    <?php echo $this->partial('library/partial-library.phtml', array('item' => $item)); ?>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>
<?php /*<div class="sub-content">
    <h2 class="border-bottom">Gallery</h2>
    <div id="myCarousel" class="bootstrap-carousel carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item">
                <div class="row-fluid">
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="row-fluid">
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="row-fluid">
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>*/?>