<div class="sub-content">
    <h2 class="border-bottom">Media</h2>
    <div class="row-fluid">
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="sub-content">
    <h2 class="border-bottom">Library</h2>
    <div class="row-fluid">
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
        <div class="span4 list-item">
            <div class="row-fluid">
                <div class="span5 thumb">
                    <img src="<?php echo $this->getResource('abc.jpg'); ?>" />
                </div>
                <div class="span7">
                    <h3 class="no-margin-top">Ya Seen</h3>
                    <p>Mishary Rashid</p>
                    <p>12:03</p>
                    <button class="btn">Play</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="sub-content">
    <h2 class="border-bottom">Gallery</h2>
    <div id="myCarousel" class="bootstrap-carousel carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item">
                <div class="row-fluid">
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="row-fluid">
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="row-fluid">
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                    <div class="span4">
                        <img src="<?php echo $this->getResource('gallery.jpg'); ?>" />
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>