<?php if ($this->error === TRUE) { ?>
    <div class="errors">Invalid credentials</div>
<?php } ?>
<div class="login-form login-form span6 offset3">
    <form method="post">
        <div class="row-fluid">
            <div class="span5">
                <label class="pull-right"><?php echo $this->form->username->getLabel(); ?></label>
            </div>
            <div class="span7">
                <?php echo $this->form->username; ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span5">
                <label class="pull-right"><?php echo $this->form->password->getLabel(); ?></label>
            </div>
            <div class="span7">
                <?php echo $this->form->password; ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span5">
                <label class="pull-right">&nbsp;</label>
            </div>
            <div class="span7">
                <input class="btn" type="submit" value="Login"/>
            </div>
        </div>
    </form>
</div>