<?php if ($this->error === TRUE) { ?>
    <div class="errors">Invalid credentials</div>
<?php } ?>
<div class="login-form span4 offset4 login-box">
    <form method="post">
        <div class="row-fluid">
            <div class="span4">
                <label class="pull-right"><?php echo $this->form->username->getLabel(); ?></label>
            </div>
            <div class="span8">
                <?php echo $this->form->username; ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <label class="pull-right"><?php echo $this->form->password->getLabel(); ?></label>
            </div>
            <div class="span8">
                <?php echo $this->form->password; ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <label class="pull-right">&nbsp;</label>
            </div>
            <div class="span8" style="margin-top: -10px;">
                <a href="#">Forgot Password</a>
            </div>
            <div class="row-fluid">
                <div class="span6 offset4">
                    <input class="btn btn-primary btn-block" type="submit" value="Login"/>
                </div>

            </div>
            <div class="row-fluid">
                <div class="span6 offset4">
                    <a class="btn btn-success btn-block">Create Account</a>
                </div>
            </div>
        </div>
    </form>
</div>