<div class="header">
    <!-- Main nav... -->
    <div class="row-fluid main-nav ui-state-default">
        <ul class="nav nav-pills pull-left">
            <li class="ear ear-top-down">
                Search
            </li>
        </ul>
        <ul class="nav nav-pills pull-right">
            <li class="active">
                <a href="homepage.html">Home</a>
            </li>
            <li>
                <a href="mediapage.html">Media</a>
            </li>
            <li>
                <a href="library.html">Library</a>
            </li>
            <li>
                <a href="gallary.html">Gallery</a>
            </li>
        </ul>
    </div>
    <!-- ...Main nav -->

    <div class="row-fluid main-nav-clearfix"></div>
    <?php if ($this->isHomepage()) { ?>
        <div class="banner"></div>
    <?php } ?>
</div>