<?php
$mostLiked = $this->getMostLiked();
?>
<div class="sidebar span3 ui-tabs ui-widget-content">
    <?php if (!empty($mostLiked['media'])) { ?>
        <div class="sidebar-section ui-widget-content ui-corner-all">
            <h5 class="sidebar-section-header ui-state-default no-margin-top ui-corner-top">Most liked media</h5>
            <div class="sidebar-section-content">
                <ul class="jquery-ui-menu">
                    <?php foreach ($mostLiked['media'] as $item) { ?>
                        <li><a href="<?php echo $this->url(array(), NULL, TRUE); ?>#media<?php echo $item->id; ?>"><?php echo $item->name; ?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    <?php } ?>
    <?php if (!empty($mostLiked['library'])) { ?>
        <div class="sidebar-section ui-widget-content ui-corner-all">
            <h5 class="sidebar-section-header ui-state-default no-margin-top ui-corner-top">Most liked library</h5>
            <div class="sidebar-section-content">
                <ul class="jquery-ui-menu">
                    <?php foreach ($mostLiked['library'] as $item) { ?>
                        <li><a href="<?php echo $this->url(array(), NULL, TRUE); ?>#library<?php echo $item->id; ?>"><?php echo $item->name; ?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    <?php } ?>
</div>