<?php if (!empty($this->radio)) { ?>
    <div class="row-fluid">
        <h3>Delete <?php echo $this->radio->title; ?></h3>
    </div>
    <div class="row-fluid">
        <p>Are you sure you want to permanently delete this radio?</p>
        <p>This action is not reversible!</p>
        <p>&nbsp;</p>
    </div>
    <div class="row-fluid">
        <div class="span2">
            <input class="btn btn-block link-to-back" value="Cancel" />
        </div>
        <div class="span2">
            <form method="post">
                <input class="btn btn-danger btn-block" type="submit" value="Delete"/>
            </form>
        </div>
    </div>
    <?php
}