<form method="post" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="span4">
            <label><?php echo $this->form->title->getLabel(); ?></label>
            <?php echo $this->form->title; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <label><?php echo $this->form->source->getLabel(); ?></label>
            <?php echo $this->form->source; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <label><?php echo $this->form->extension->getLabel(); ?></label>
            <?php echo $this->form->extension; ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <label><?php echo $this->form->status->getLabel(); ?></label>
            <?php echo $this->form->status; ?>
        </div>
    </div>
    <div class="row-fluid">&nbsp;</div>
    <div class="row-fluid">
        <div class="span3">
            <input class="btn btn-primary btn-block btn-input" type="submit" value="Save"/>
        </div>
    </div>
</form>